#!/usr/bin/env python

import csv
import re
import os
import sys

# Define the input and output file paths
# Assuming the script is run from the backend/ directory where the CSV is located
input_csv_path = 'NLP documents bank - Sheet1.csv'
output_csv_path = 'NLP documents bank - Sheet1_cleaned.csv'

# Define label mappings for standardization and removal
# Keys are the raw labels (case-insensitive match), values are the standardized labels.
# Labels not in the mapping will be kept as is. Explicit None values will still be removed.
label_mapping = {
    # Generalized Topic Labels
    'finance': 'Business/Finance',
    'economics': 'Business/Finance',
    'business': 'Business/Finance',
    'marketing': 'Business/Finance',
    'international trade': 'Business/Finance',
    'real estate': 'Business/Finance',
    'financial oversight': 'Business/Finance',
    'private equity': 'Business/Finance',
    'banking sector': 'Business/Finance',
    'crypto trends': 'Technology',
    'blockchain infrastructure': 'Technology',
    'agile cryptography': 'Technology',
    'industry challenges': 'Business/Finance',
    'market analysis': 'Business/Finance',
    'market performance': 'Business/Finance',
    'sales forecasting': 'Business/Finance',
    'sales management': 'Business/Finance',
    'sales strategy': 'Business/Finance',
    'financial crimes': 'Politics/Law',
    'money laundering': 'Politics/Law',
    'valuation methods': 'Business/Finance',
    'venture capital': 'Business/Finance',
    'm&a': 'Business/Finance',
    'hr alignment': 'Business/Finance',
    'human resources': 'Business/Finance',
    'hr': 'Business/Finance',
    'training': 'Business/Finance',
    'workforce development': 'Business/Finance',
    'employment': 'Business/Finance',
    'hr theory': 'Business/Finance',
    'strategic hr': 'Business/Finance',
    'hr practices': 'Business/Finance',
    'work psychology': 'Health',
    'labor economics': 'Business/Finance',
    'workforce trends': 'Business/Finance',
    'performance': 'Business/Finance',
    'workplace communication': 'Business/Finance',
    'change management': 'Business/Finance',
    'leadership': 'Business/Finance',
    'future of work': 'Business/Finance',
    'talent strategy': 'Business/Finance',
    'retention': 'Business/Finance',
    'people analytics': 'Business/Finance',
    'talent retention': 'Business/Finance',
    'hr tech': 'Technology',
    'human capital': 'Business/Finance',
    'workforce strategy': 'Business/Finance',
    'hiring': 'Business/Finance',
    'skills gap': 'Business/Finance',
    'hr design': 'Business/Finance',
    'behavioral science': 'Health',
    'metrics': 'Business/Finance',
    'alignment': 'Business/Finance',
    'workforce modeling': 'Business/Finance',
    'engagement': 'Business/Finance',
    'experience metrics': 'Business/Finance',
    'shrm theory': 'Business/Finance',
    'hr compliance': 'Politics/Law',
    'policy development': 'Politics/Law',
    'ethics': 'Politics/Law',
    'hr capstone': 'Business/Finance',
    'practical application': 'Business/Finance',
    'hr trends': 'Business/Finance',
    'global talent': 'Business/Finance',
    'future workforce': 'Business/Finance',
    'strategy': 'Business/Finance',
    'talent management': 'Business/Finance',
    'lifecycle': 'Business/Finance',
    'immigration': 'Politics/Law',
    'global hr': 'Business/Finance',
    'dei': 'Business/Finance',
    'inclusion strategies': 'Business/Finance',
    'risk': 'Business/Finance',
    'public sector hr': 'Politics/Law',
    'tech tools': 'Technology',
    'automation': 'Technology',
    'analytics': 'Business/Finance',
    'insights': 'Business/Finance',
    'esg': 'Environment/Sustainability',
    'sustainability': 'Environment/Sustainability',
    'pandemic': 'Health',
    'remote work': 'Business/Finance',
    'pay strategy': 'Business/Finance',
    'benchmarking': 'Business/Finance',
    'labor': 'Business/Finance',
    'labor market trends': 'Business/Finance',
    'workforce': 'Business/Finance',

    'technology': 'Technology',
    'ai': 'Technology',
    'artificial intelligence': 'Technology',
    'machine learning': 'Technology',
    'nlp': 'Technology',
    'deep learning': 'Technology',
    'computer science': 'Technology',
    'mobile devices': 'Technology',
    'semiconductors': 'Technology',
    'ai hardware': 'Technology',
    'social chat': 'Technology',
    'translation ai': 'Technology',
    'networking': 'Technology',
    'ai integration': 'Technology',
    'enterprise ai': 'Business/Finance',
    'data platforms': 'Technology',
    'computing research': 'Research/Academia',
    'human-computer interaction': 'Technology',
    'scientific discovery': 'Research/Academia',
    'cryptography': 'Technology',
    'lattice theory': 'Technology',
    'data science': 'Technology',
    'text analysis': 'Technology',
    'digital humanities': 'Research/Academia',
    'cybersecurity': 'Security',
    'risk analysis': 'Business/Finance',
    'information technology': 'Technology',
    'software development': 'Technology',
    'information systems': 'Technology',
    'text analytics': 'Technology',
    'developer tools': 'Technology',
    'user experience': 'Technology',
    'model evaluation': 'Technology',
    'computer vision': 'Technology',
    'ai platforms': 'Technology',
    'cloud': 'Technology',
    'ai assistants': 'Technology',
    'collaboration': 'Business/Finance',
    'crm': 'Business/Finance',
    'ai acceleration': 'Technology',
    'creative tools': 'Technology',
    'music tech': 'Lifestyle/Culture',
    'speech ai': 'Technology',
    'enterprise software': 'Business/Finance',
    'multimodal models': 'Technology',
    'chatgpt': 'Technology',
    'chat interfaces': 'Technology',
    'model lifecycle': 'Technology',
    'api': 'Technology',
    'surveys': 'Research/Academia',
    'generative ai': 'Technology',
    'multimodal ai': 'Technology',
    'model availability': 'Technology',
    'model analysis': 'Technology',
    'startups': 'Business/Finance',
    'hardware': 'Technology',
    'social media': 'Lifestyle/Culture',

    'research': 'Research/Academia',
    'science': 'Research/Academia',
    'research trends': 'Research/Academia',
    'research analysis': 'Research/Academia',
    'academia': 'Research/Academia',
    'research methodology': 'Research/Academia',
    'research policy': 'Research/Academia',
    'open science': 'Research/Academia',
    'library science': 'Research/Academia',
    'academic publications': 'Research/Academia',
    'legal research': 'Research/Academia',
    'legal studies': 'Politics/Law',
    'scientific research': 'Research/Academia',
    'research evaluation': 'Research/Academia',
    'research metrics': 'Research/Academia',
    'cryptology': 'Technology',
    'formal verification': 'Technology',
    'cryptography topics': 'Technology',
    'applied cryptology': 'Technology',
    '2024 publications': 'Research/Academia',
    'journal articles': 'Research/Academia',
    'complexity measures': 'Technology',
    'block cipher cryptanalysis': 'Technology',
    'arxiv preprints': 'Research/Academia',
    'legal scholarship': 'Research/Academia',

    'sports': 'Sports',

    'health': 'Health',
    'healthcare': 'Health',
    'mental health': 'Health',
    'public health': 'Health',
    'epidemiology': 'Health',
    'global health': 'Health',
    'healthcare workforce': 'Health',
    'medicine': 'Health',
    'clinical research': 'Research/Academia',
    'infectious diseases': 'Health',
    'digital health': 'Technology',
    'global health funding': 'Business/Finance',
    'global health policy': 'Politics/Law',
    'psychology': 'Health',
    'personal development': 'Lifestyle/Culture',
    'biology': 'Research/Academia',

    'law': 'Politics/Law',
    'land law': 'Politics/Law',
    'politics': 'Politics/Law',
    'public policy': 'Politics/Law',
    'international relations': 'Politics/Law',
    'geopolitics': 'Politics/Law',
    'tax policy': 'Politics/Law',
    'transportation policy': 'Politics/Law',
    'national security': 'Politics/Law',
    'government operations': 'Politics/Law',
    'military cooperation': 'Politics/Law',
    'counterterrorism': 'Politics/Law',
    'international justice': 'Politics/Law',
    'political science': 'Politics/Law',
    'regulatory standards': 'Politics/Law',
    'copyright law': 'Politics/Law',
    'patent law': 'Politics/Law',
    'appropriations': 'Politics/Law',
    'federal law': 'Politics/Law',
    'legal language models': 'Technology',
    'case law prediction': 'Technology',
    'corporate governance': 'Business/Finance',
    'constitutional law': 'Politics/Law',
    'legal profession': 'Politics/Law',
    'global legal developments': 'Politics/Law',
    'case law': 'Legal/Policy',
    'sentencing guidelines': 'Politics/Law',
    'legal writing': 'Research/Academia',
    'citation standards': 'Research/Academia',
    'local legislation': 'Politics/Law',
    'emergency management': 'Politics/Law',
    'legal industry trends': 'Business/Finance',
    'law firm growth': 'Business/Finance',
    'legal technology': 'Technology',
    'general counsel': 'Politics/Law',
    'legal strategy': 'Politics/Law',
    'employment law': 'Politics/Law',
    'california labor laws': 'Politics/Law',
    'legal ai': 'Technology',
    'legal operations': 'Business/Finance',
    'corporate legal': 'Politics/Law',
    'intellectual property': 'Politics/Law',
    'privacy': 'Politics/Law',
    'access to justice': 'Politics/Law',
    'legal data': 'Politics/Law',
    'llms': 'Technology',
    'legal accuracy': 'Politics/Law',
    'legal text analytics': 'Technology',
    'india': 'Politics/Law',
    'jurisprudence': 'Politics/Law',
    'legal theory': 'Politics/Law',
    'democratic ideals': 'Politics/Law',
    'public law': 'Politics/Law',
    'various legal topics': 'Politics/Law',
    'political economy': 'Business/Finance',
    'global politics': 'Politics/Law',
    'various ir topics': 'Politics/Law',
    'un sanctions': 'Politics/Law',
    'u.s.-china relations': 'Politics/Law',
    'economic strategy': 'Business/Finance',
    'u.s. foreign policy': 'Politics/Law',
    'global conflicts': 'Politics/Law',
    'southeast asia': 'Politics/Law',
    'u.s. military policy': 'Politics/Law',
    'engineering': 'Technology',
    'information retrieval': 'Technology',
    'information extraction': 'Technology',
    'language documentation': 'Research/Academia',
    'authorship analysis': 'Research/Academia',
    'document processing': 'Technology',
    'speech processing': 'Technology',
    'neuro-symbolic ai': 'Technology',
    'interpretability': 'Technology',
    'brain science': 'Health',
    'accessibility': 'General',
    'molecular dynamics': 'Research/Academia',
    'reinforcement learning': 'Technology',
    'materials science': 'Research/Academia',
    'media studies': 'Lifestyle/Culture',
    'manufacturing': 'Business/Finance',
    'content marketing': 'Business/Finance',
    'education policy': 'Education',
    'student assessment': 'Education',
    'hr analytics': 'Business/Finance',
    'workforce transformation': 'Business/Finance',
    'asymmetric encryption': 'Technology',
    'cryptographic techniques': 'Technology',
    'data security': 'Security',
    'cryptographic methods': 'Technology',
    'authentication': 'Security',
    'information theory': 'Research/Academia',
    'cryptographic applications': 'Technology',
    'practical implementations': 'Technology',
    'high-dimensional systems': 'Research/Academia',
    'applied cryptography': 'Technology',
    'textbook': 'Education',
    'lfsr': 'Technology',
    'hash functions': 'Technology',
    'mathematics': 'Research/Academia',
    'reference book': 'Research/Academia',
    'classical cryptography': 'Technology',
    'quantum computing': 'Technology',
    'formal verification': 'Technology',
    'post-quantum cryptography': 'Technology',
    'nist standards': 'Security',
    'organizational readiness': 'Business/Finance',
    'iot security': 'Security',
    'data protection': 'Security',
    'applied cryptology': 'Technology',
    'complexity measures': 'Research/Academia',
    'block cipher cryptanalysis': 'Technology',
    'encryption risks': 'Security',
    'bfsi sector': 'Business/Finance',
    'data analysis': 'Business/Finance',
    'ai in transportation': 'Technology',
    'budgeting': 'Business/Finance',
    'freight market': 'Business/Finance',
    'logistics': 'Business/Finance',
    'future outlook': 'Business/Finance',
    'industry trends': 'Business/Finance',
    'federated learning': 'Technology',
    'intelligent transportation': 'Transportation',
    'graph neural networks': 'Technology',
    'object detection': 'Technology',
    'planning': 'General',
    'interdisciplinary transportation research': 'Research/Academia',
    'technical papers': 'Research/Academia',
    'systems': 'Technology',
    'research digest': 'Report/Study',
    'emergency transportation': 'Transportation',
    'accident report': 'Transportation',
    'traffic congestion': 'Transportation',
    'road travel': 'Transportation',
    'public transportation': 'Transportation',
    'autonomous vehicles': 'Technology',
    'public health crisis': 'Health',
    'driver shortage': 'Business/Finance',
    'air travel': 'Tourism',
    'policy': 'Politics/Law',
    'circulars': 'Research/Academia',
    'research circulars': 'Research/Academia',
    'whitepapers': 'Report/Study',
    'back office efficiency': 'Business/Finance',
    'innovation': 'General',
    'infrastructure': 'Politics/Law',
    'strategic research': 'Research/Academia',
    'asphalt mixtures': 'General',
    'federal judiciary': 'Politics/Law',
    'caseload statistics': 'Politics/Law',
    'data management': 'Technology',
    'digital products': 'Business/Finance',
    'legislation': 'Politics/Law',
    'case law prediction': 'Technology',
    'legal industry trends': 'Business/Finance',
    'law firm growth': 'Business/Finance',
    'legal ai': 'Technology',
    'contract review': 'Legal/Policy',
    'legal operations': 'Business/Finance',
    'corporate legal': 'Business/Finance',
    'intellectual property': 'Politics/Law',
    'privacy': 'Politics/Law',
    'access to justice': 'Politics/Law',
    'legal data': 'Politics/Law',
    'legal accuracy': 'Politics/Law',
    'legal text analytics': 'Technology',
    'india': 'Politics/Law',
    'jurisprudence': 'Politics/Law',
    'legal theory': 'Politics/Law',
    'democratic ideals': 'Politics/Law',
    'public law': 'Politics/Law',
    'various legal topics': 'Politics/Law',
    'faculty rankings': 'Research/Academia',
    'research study': 'Research/Academia',
    'political economy': 'Business/Finance',
    'global politics': 'Politics/Law',
    'various ir topics': 'Politics/Law',
    'un sanctions': 'Politics/Law',
    'u.s.-china relations': 'Politics/Law',
    'economic strategy': 'Business/Finance',
    'u.s. foreign policy': 'Politics/Law',
    'global conflicts': 'Politics/Law',
    'southeast asia': 'Politics/Law',
    'u.s. military policy': 'Politics/Law',
    'development': 'General',
    'open access': 'Research/Academia',
    'global climate policy': 'Environment/Sustainability',
    'latin american perspectives': 'Politics/Law',


    'education': 'Education',
    'basic education': 'Education',
    'higher ed trends': 'Education',
    'future skills': 'Business/Finance',
    'edtech': 'Technology',
    'student engagement': 'Education',
    'teaching methods': 'Education',
    'digital learning': 'Education',
    'education finance': 'Business/Finance',
    'teacher survey': 'Education',
    'learning recovery': 'Education',
    'online learning': 'Education',
    'global learning': 'Education',
    'unicef strategy': 'Politics/Law',
    'ict4e': 'Technology',
    'future of education': 'Education',
    'flipped learning': 'Education',
    'moocs': 'Education',
    'vr': 'Technology',
    'online quality': 'Education',
    'covid impact': 'Health',
    'higher ed': 'Education',
    'gamification': 'Education',
    'class size': 'Education',
    'stem': 'Education',
    'primary': 'Education',
    'oer': 'Education',
    'edtech evidence': 'Technology',
    'global trends': 'Business/Finance',
    'conflict & education': 'Politics/Law',
    'equity': 'Education',
    'mobile learning': 'Technology',
    'ar': 'Technology',
    'digital strategy': 'Business/Finance',
    'covid teaching': 'Education',
    'learning crisis': 'Education',
    'teacher status': 'Education',
    'global partnership': 'Politics/Law',
    'homework': 'Education',
    'teacher burnout': 'Business/Finance',
    'assessment': 'Education',
    'pbl': 'Education',
    'remote learning': 'Education',
    'usa': 'Politics/Law',
    'education statistics': 'Education',

    'tourism': 'Tourism',
    'sustainable tourism': 'Tourism',
    'travel': 'Tourism',
    'adventure': 'Tourism',
    'ecotourism': 'Tourism',
    'smart tourism': 'Technology',
    'inclusive tourism': 'Tourism',
    'volunteer tourism': 'Tourism',
    'rural tourism': 'Tourism',
    'urban tourism': 'Tourism',
    'tourism geographies': 'Tourism',
    'tourism planning': 'Tourism',
    'tourism management': 'Tourism',
    'tourism research': 'Research/Academia',
    'tourism statistics': 'Tourism',
    'travel behavior': 'Tourism',
    'travel guide': 'Tourism',
    'travel industry': 'Business/Finance',
    'travel research': 'Research/Academia',
    'travel statistics': 'Tourism',
    'travel technology': 'Technology',

    'environment': 'Environment/Sustainability',
    'climate change': 'Environment/Sustainability',
    'environmental policy': 'Politics/Law',
    'nature': 'Environment/Sustainability',
    'sustainable energy': 'Environment/Sustainability',
    'environmental impacts': 'Environment/Sustainability',
    'environmental regulations': 'Politics/Law',
    'environmental science': 'Environment/Sustainability',
    'environmental studies': 'Environment/Sustainability',
    'marine pollution': 'Environment/Sustainability',
    'plastic waste mitigation': 'Environment/Sustainability',
    'sustainable agriculture': 'Environment/Sustainability',
    'sustainable development': 'Environment/Sustainability',
    'sustainable energy systems': 'Environment/Sustainability',
    'sustainable finance': 'Business/Finance',
    'sustainable forest management': 'Environment/Sustainability',
    'sustainable land management': 'Environment/Sustainability',
    'sustainable livelihoods': 'Business/Finance',
    'sustainable materials': 'Environment/Sustainability',
    'sustainable practices': 'Environment/Sustainability',
    'sustainable resource management': 'Environment/Sustainability',
    'sustainable transportation': 'Transportation',
    'sustainable urban development': 'Environment/Sustainability',
    'sustainable water management': 'Environment/Sustainability',

    'food': 'Food',
    'recipe': 'Food',
    'vegan cuisine': 'Food',
    'food waste reduction': 'Environment/Sustainability',

    'culture': 'Lifestyle/Culture',
    'heritage': 'Lifestyle/Culture',
    'literature': 'Lifestyle/Culture',
    'arts': 'Lifestyle/Culture',
    'culture shift': 'Business/Finance',
    'organizational culture': 'Business/Finance',
    'lifestyle': 'Lifestyle/Culture',

    'space exploration': 'Space',
    'astrobiology': 'Space',
    'space technology': 'Technology',
    'space policy': 'Politics/Law',
    'space missions': 'Space',
    'space operations': 'Space',

    # Adding mappings for previously observed specific labels
    'security': 'Security', # Keeping Security as its own top-level category for now
    'diversity': 'Business/Finance', # Mapping Diversity to Business/Finance based on dataset context
    'engineering': 'Technology',
    'information retrieval': 'Technology',
    'information extraction': 'Technology',
    'language documentation': 'Research/Academia',
    'authorship analysis': 'Research/Academia',
    'document processing': 'Technology',
    'speech processing': 'Technology',
    'neuro-symbolic ai': 'Technology',
    'interpretability': 'Technology',
    'brain science': 'Health',
    'accessibility': 'General',
    'molecular dynamics': 'Research/Academia',
    'reinforcement learning': 'Technology',
    'materials science': 'Research/Academia',
    'media studies': 'Lifestyle/Culture',
    'manufacturing': 'Business/Finance',
    'content marketing': 'Business/Finance',
    'education policy': 'Education',
    'student assessment': 'Education',
    'hr analytics': 'Business/Finance',
    'workforce transformation': 'Business/Finance',
    'asymmetric encryption': 'Technology',
    'cryptographic techniques': 'Technology',
    'data security': 'Security',
    'cryptographic methods': 'Technology',
    'authentication': 'Security',
    'information theory': 'Research/Academia',
    'cryptographic applications': 'Technology',
    'practical implementations': 'Technology',
    'high-dimensional systems': 'Research/Academia',
    'applied cryptography': 'Technology',
    'textbook': 'Education',
    'lfsr': 'Technology',
    'hash functions': 'Technology',
    'mathematics': 'Research/Academia',
    'reference book': 'Research/Academia',
    'classical cryptography': 'Technology',
    'quantum computing': 'Technology',
    'formal verification': 'Technology',
    'post-quantum cryptography': 'Technology',
    'nist standards': 'Security',
    'organizational readiness': 'Business/Finance',
    'iot security': 'Security',
    'data protection': 'Security',
    'applied cryptology': 'Technology',
    'complexity measures': 'Research/Academia',
    'block cipher cryptanalysis': 'Technology',
    'encryption risks': 'Security',
    'bfsi sector': 'Business/Finance',
    'data analysis': 'Business/Finance',
    'ai in transportation': 'Technology',
    'budgeting': 'Business/Finance',
    'freight market': 'Business/Finance',
    'logistics': 'Business/Finance',
    'future outlook': 'Business/Finance',
    'industry trends': 'Business/Finance',
    'federated learning': 'Technology',
    'intelligent transportation': 'Transportation',
    'graph neural networks': 'Technology',
    'object detection': 'Technology',
    'planning': 'General',
    'interdisciplinary transportation research': 'Research/Academia',
    'technical papers': 'Research/Academia',
    'systems': 'Technology',
    'research digest': 'Report/Study',
    'emergency transportation': 'Transportation',
    'accident report': 'Transportation',
    'traffic congestion': 'Transportation',
    'road travel': 'Transportation',
    'public transportation': 'Transportation',
    'autonomous vehicles': 'Technology',
    'public health crisis': 'Health',
    'driver shortage': 'Business/Finance',
    'air travel': 'Tourism',
    'policy': 'Politics/Law',
    'circulars': 'Research/Academia',
    'research circulars': 'Research/Academia',
    'whitepapers': 'Report/Study',
    'back office efficiency': 'Business/Finance',
    'innovation': 'General',
    'infrastructure': 'Politics/Law',
    'strategic research': 'Research/Academia',
    'asphalt mixtures': 'General',
    'federal judiciary': 'Politics/Law',
    'caseload statistics': 'Politics/Law',
    'data management': 'Technology',
    'digital products': 'Business/Finance',
    'legislation': 'Politics/Law',
    'case law prediction': 'Technology',
    'legal industry trends': 'Business/Finance',
    'law firm growth': 'Business/Finance',
    'legal ai': 'Technology',
    'contract review': 'Legal/Policy',
    'legal operations': 'Business/Finance',
    'corporate legal': 'Business/Finance',
    'intellectual property': 'Politics/Law',
    'privacy': 'Politics/Law',
    'access to justice': 'Politics/Law',
    'legal data': 'Politics/Law',
    'legal accuracy': 'Politics/Law',
    'legal text analytics': 'Technology',
    'india': 'Politics/Law',
    'jurisprudence': 'Politics/Law',
    'legal theory': 'Politics/Law',
    'democratic ideals': 'Politics/Law',
    'public law': 'Politics/Law',
    'various legal topics': 'Politics/Law',
    'faculty rankings': 'Research/Academia',
    'research study': 'Research/Academia',
    'political economy': 'Business/Finance',
    'global politics': 'Politics/Law',
    'various ir topics': 'Politics/Law',
    'un sanctions': 'Politics/Law',
    'u.s.-china relations': 'Politics/Law',
    'economic strategy': 'Business/Finance',
    'u.s. foreign policy': 'Politics/Law',
    'global conflicts': 'Politics/Law',
    'southeast asia': 'Politics/Law',
    'u.s. military policy': 'Politics/Law',
    'development': 'General',
    'open access': 'Research/Academia',
    'global climate policy': 'Environment/Sustainability',
    'latin american perspectives': 'Politics/Law',


    # Further Generalized Document Type Labels
    'white paper': 'Report/Study',
    'whitepapers': 'Report/Study',
    'technical report': 'Report/Study',
    'report': 'Report/Study',
    'annual report': 'Report/Study',
    'government report': 'Report/Study',
    'case study': 'Report/Study',
    'situation report': 'Report/Study',
    'disease update': 'Report/Study',
    'policy report': 'Report/Study',
    'study': 'Report/Study',
    'survey report': 'Report/Study',
    'progress report': 'Report/Study',
    'survey': 'Report/Study',
    'statistical report': 'Report/Study',
    'research digest': 'Report/Study',
    'research circular': 'Report/Study',
    'report/study': 'Report/Study',
    'draft whitepaper': 'Report/Study',
    'policy brief': 'Report/Study',
    'government whitepaper': 'Report/Study',
    'risk assessment': 'Report/Study',
    'market report': 'Report/Study',
    'un report': 'Report/Study',
    'reports': 'Report/Study',
    'white papers': 'Report/Study',


    'technical guide': 'Guide/Manual',
    'user guide': 'Guide/Manual',
    'informational guide': 'Guide/Manual',
    'guide': 'Guide/Manual',
    'manual': 'Guide/Manual',
    'style manual': 'Guide/Manual',
    'handbook': 'Guide/Manual',
    'guide/manual': 'Guide/Manual',
    'framework': 'Guide/Manual',
    'competency framework': 'Guide/Manual',
    'security framework': 'Guide/Manual',
    'toolkit': 'Guide/Manual',
    'user manual': 'Guide/Manual',
    'template': 'Guide/Manual', # Mapping Template to Guide/Manual


    'news': 'Article/News',
    'news article': 'Article/News',
    'news articles': 'Article/News',
    'magazine article': 'Article/News',
    'article': 'Article/News',
    'news release': 'Article/News',
    'daily update': 'Article/News',
    'announcement': 'Article/News',
    'press release': 'Article/News',
    'article/news': 'Article/News',
    'legal update': 'Article/News',
    'blog post': 'Article/News',
    'blog': 'Article/News',

    'job application form': 'Application Form',
    'university admission application form': 'Application Form',
    'visa application form': 'Application Form',
    'flexible work arrangement application form': 'Application Form',
    'application form': 'Application Form',

    'research paper': 'Research/Academic',
    'research papers': 'Research/Academic',
    'systematic review': 'Research/Academic',
    'survey paper': 'Research/Academic',
    'workshop paper': 'Research/Academia',
    'seminal paper': 'Research/Academia',
    'review paper': 'Research/Academic',
    'arxiv preprint': 'Research/Academia',
    'academic articles': 'Research/Academia',
    'research articles': 'Research/Academia',
    'research collection': 'Research/Academia',
    'journal': 'Research/Academia',
    'journal issue': 'Research/Academia',
    'conference paper': 'Research/Academia',
    'conference proceedings': 'Research/Academia',
    'online repository': 'Research/Academia',
    'index': 'Research/Academia',
    'academic publications': 'Research/Academia',
    'research study': 'Research/Academia',
    'research/academic': 'Research/Academic',
    'policy research': 'Research/Academia',
    'journal article': 'Research/Academic',


    'policy document': 'Legal/Policy',
    'legal document': 'Legal/Policy',
    'guidance document': 'Legal/Policy',
    'legislation': 'Legal/Policy',
    'court opinions': 'Legal/Policy',
    'legal/policy': 'Legal/Policy',
    'contract review': 'Legal/Policy',
    'court judgment': 'Legal/Policy', # Mapping court judgment to Legal/Policy


    'questionnaire': 'Questionnaire',
    'survey instrument': 'Questionnaire',

    'brochure': 'Brochure',

    'transcript': 'Informational Text',
    'interview transcript': 'Informational Text',
    'encyclopedia entry': 'Informational Text',
    'informational text': 'Informational Text',
    'book summary': 'Informational Text',
    'factsheet': 'Informational Text',
    'web resource': 'Informational Text',
    'press conference': 'Informational Text',
    'press briefing': 'Informational Text',
    'briefing': 'Informational Text',
    'government reports': 'Report/Study', # Mapping government reports to Report/Study


    'presentation pdf': 'Presentation',
    'presentation': 'Presentation',
    'presentation slides': 'Presentation',

    'recipe': 'Food',

    'product review': 'Review',
    'review': 'Review',

    'online course': 'Education',
    'educational resource': 'Education',

    # Labels to be excluded (Sources or irrelevant) - These will still be excluded if mapped to None
    'jmir': None,
    'reuters': None,
    'samsung': None,
    'wikipedia – die freie enzyklopädie': None,
    'gosling.psy.utexas.edu': None,
    'evaluationframework.sportengland.org': None,
    'rand corporation': None,
    'digital library': None,
    'nasa history division': None,
    'ft': None,
    'ala': None,
    'acrl': None,
    'issues': None,
    'diversity atlas': None,
    'phd direction': None,
    'world economic forum': None,
    'new yorker': None,
    'argophilia': None,
    'traveldailynews': None,
    'who': None,
    'australiancybersecuritymagazine': None,
    'communitymedicine4asses': None,
    'linkedin': None,
    'gds.earth': None,
    'nist': None,
    'nasa-dares': None,
    'cisa': None,
    'pk': None,
    'eu': None,
    'us': None,
    'uk': None,
    'pwc': None,
    'qualtrics': None,
    'mit sloan': None,
    'cipd': None,
    'josh bersin': None,
    'mckinsey': None,
    'payscale': None,
    'ijtre': None,
    'eajournals': None,
    'ijaem': None,
    'researchgate': None,
    'stanford': None,
    'princeton': None,
    'cambridge': None,
    'iacr': None,
    'entrust': None,
    'encryption consulting': None,
    'mdpi': None,
    'axios': None,
    'the times': None,
    'wired': None,
    'myjournalcourier': None,
    'houstonchronicle': None,
    'hopskipdrive': None,
    'transportation choices coalition': None,
    'trb': None,
    'ti-insight.com': None,
    'ttnews.com': None,
    'nltd.com': None,
    'govwhitepapers.com': None,
    'supremecourt.gov': None,
    'uscourts.gov': None,
    'treasury.gov': None,
    'sba.gov': None,
    'copyright.gov': None,
    'federalregister.gov': None,
    'mtc.gov': None,
    'congress.gov': None,
    'law.umn.edu': None,
    'law.northwestern.edu': None,
    'ssrn.com': None,
    'digitalcommons.wcl.american.edu': None,
    'clp.law.harvard.edu': None,
    'z.umn.edu': None,
    'ussc.gov': None,
    'nycourts.gov': None,
    'nyc.gov': None,
    'leopardsolutions.com': None,
    'law.stanford.edu': None,
    'ftitechnology.com': None,
    'calchamber.com': None,
    'robinai.com': None,
    'the-innovative-lawyer.squarespace.com': None,
    'netdocuments.com': None,
    'simplelegal.com': None,
    'iab.com': None,
    'justice.gov': None,
    'tandfonline.com': None,
    'law.ed.ac.uk': None,
    'cornell.legal-studies.ssrn.com': None,
    'loc.gov': None,
    'legaltechconnection.com': None,
    'cidob.org': None,
    'cfr.org': None,
    'state.gov': None,
    'foreignaffairs.gov.fj': None,
    'carnegieendowment.org': None,
    'globalaffairs.org': None,
    'apnews.com': None,
    'washingtonpost.com': None,
    'arcadia.edu': None,
    'thebrpi.org': None,
    'bepress.com': None,
    'pmc': None,
    'arxiv': None,
    'jm': None,
    'ted': None,
    'congress.gov | library of congress': None,
    'american psychological association': None,
    'elsevier': None,
    'springer': None,
    'wiley': None,
    'taylor & francis online': None,
    'sage publications': None,
    'nature': None,
    'frontiers': None,
    'aea': None,
    'shrm': None,
    'gartner': None,
    'lattice': None,
    'ibm': None,
    'deloitte': None,
    'google': None,
    'microsoft': None,
    'salesforce': None,
    'nvidia': None,
    'adobe': None,
    'spotify': None,
    'tiktok': None,
    'zoom': None,
    'intel': None,
    'meta': None,
    'cisco': None,
    'openai': None,
    'anthropic': None,
    'adept': None,
    'adobe firefly': None,
    'chatgpt enterprise': None,
    'watsonx': None,
    'gaudi 3': None,
    'claude 3': None,
    'bedrock': None,
    'gpt-4 with vision': None,
    'gpt-4': None,
    'gpt-4o': None,
    'gpt-4 turbo': None,
    'google ai test kitchen': None,
    'sweep': None,
    'outset': None,
    'momentix': None,
    'photoshop': None,
    'messenger': None,
    'teams': None,
    'sales cloud': None,
    'a100s': None,
    'firefly': None,
    'nltk': None,
    'spacy': None,

    # Added mappings for specific topic labels observed in cleaned data
    'public-key cryptography': 'Security',
    'information security': 'Security',
    'encryption algorithms': 'Security',
    'block ciphers': 'Security',
    'quantum key distribution': 'Technology',
    'quantum security': 'Security',
    'key distribution': 'Technology',
    'security goals': 'Security',
    'stream ciphers': 'Technology',
    'public key': 'Security',
    'cryptoanalysis': 'Security',
    'secure communication': 'Security',
    'pki': 'Security',
    'encryption strategies': 'Security',
    'symmetric-key primitives': 'Technology',
    'pseudo-random sequences': 'Technology',
    'key space partitioning': 'Technology',
    'cryptography research': 'Research/Academia',
    'quantum threats': 'Security',
    'smart transportation': 'Transportation',
    'organ transplants': 'Health',
    'safety audit': 'Business/Finance',
    'consumer protection': 'Business/Finance',
    'disability rights': 'Politics/Law',
    'federal courts': 'Politics/Law',
    'judicial independence': 'Politics/Law',
    'foia': 'Politics/Law',
    'media strategy': 'Business/Finance',
    'global governance': 'Politics/Law',
    'dual-use tech': 'Technology',
    'diplomacy': 'Politics/Law',
    'conflict forecasting': 'Politics/Law',
    'international relation': 'Politics/Law',
    'global affairs': 'Politics/Law',
    'global strategy': 'Business/Finance',
    'global mobility': 'Business/Finance',
    'book recommendations': 'Lifestyle/Culture',
    'reference': 'Research/Academia',
    'digest': 'Report/Study',
    'corporate law': 'Politics/Law',
    'law and economics': 'Business/Finance',
    'ai governance': 'Politics/Law',
    'ai in law': 'Technology',
    'model release': 'Technology',

    # Further refined topic label mappings based on recent train_model output
    'future of hr': 'Business/Finance',
    'global hotspots': 'Politics/Law',
    'international policy': 'Politics/Law',
    'international security': 'Politics/Law',
    'military strategy': 'Politics/Law',
    'governance': 'Politics/Law',
    'secret key': 'Security',
    'security protocols': 'Security',
    'robustness': 'Technology',
    'history': 'Research/Academia',
    'compliance': 'Business/Finance', # Mapping compliance to Business/Finance
    # 'legal/policy': 'Politics/Law', # This is a document type, should not be a topic.
                                     # Ensure logic in main loop correctly handles this.

}

def standardize_labels(labels_string, label_mapping):
    """Splits labels string, standardizes each label, keeps unique valid ones.
    Labels not explicitly mapped to None will be kept (either standardized or original).
    """
    raw_labels = [label.strip() for label in labels_string.split(',') if label.strip()]
    standardized_labels_set = set() # Use a set to store unique standardized labels

    for label in raw_labels:
        current_label = label.strip()
        current_label_lower = current_label.lower()
        resolved_label = current_label # Start with the original label as the potential resolved label

        # Track visited labels to detect cycles
        visited = set()
        visited.add(current_label_lower)

        while current_label_lower in label_mapping:
            next_label = label_mapping.get(current_label_lower)

            if next_label is None:
                # Explicitly mapped to None, discard this label chain
                resolved_label = None
                break
            elif isinstance(next_label, str) and next_label.strip():
                # Valid string mapping, continue following the chain
                resolved_label = next_label.strip() # Update resolved label to the current mapping result
                current_label_lower = resolved_label.lower()
                if current_label_lower in visited:
                    print(f"Warning: Cycle detected for label '{label}' during standardization. Path: {' -> '.join(visited)} -> {next_label}. Stopping.")
                    # Keep the last valid resolved_label before the cycle
                    break
                visited.add(current_label_lower)
            else:
                # Mapping value is not a valid string (e.g., empty string, or unexpected type)
                # Keep the last valid resolved_label before this point, or the original if no valid mapping was followed
                break # Stop following the chain if mapping is not a valid string

        # Add the resolved label if it's a non-empty string.
        # If the original label was in the mapping and mapped to a valid string, that standardized label is added.
        # If the original label was not in the mapping, it is kept.
        if isinstance(resolved_label, str) and resolved_label.strip():
            standardized_labels_set.add(resolved_label.strip())
        # If the original label was not mapped (i.e., not in label_mapping keys) and not mapped to None,
        # keep the original label (unless it's empty or whitespace).
        elif current_label_lower not in label_mapping and current_label.strip():
             standardized_labels_set.add(current_label.strip())

    # Return as a sorted list for consistency
    return sorted(list(standardized_labels_set))

# Read the CSV and write the cleaned data to a new CSV
cleaned_data = []

# Check if the input file exists using the relative path
if not os.path.exists(input_csv_path):
    print(f"Error: Input file not found at {input_csv_path}")
    sys.exit(1) # Exit after printing the path

print(f"Reading input file: {input_csv_path}")
with open(input_csv_path, mode='r', encoding='utf-8') as infile:
    reader = csv.DictReader(infile)
    fieldnames = reader.fieldnames
    
    if 'Topic Labels' not in fieldnames or 'Type Labels' not in fieldnames:
        print("Error: CSV must contain 'Topic Labels' and 'Type Labels' columns.")
        sys.exit(1)

    for row in reader:
        print(f"Processing document ID: {row.get('Document ID', 'N/A')}")
        # Standardize Topic Labels (returns a list of unique standardized topics)
        raw_topic_labels_string = row.get('Topic Labels', '')
        
        # Process each raw topic label through standardize_labels individually
        standardized_topic_labels = set()
        for raw_topic_label in [label.strip() for label in raw_topic_labels_string.split(',') if label.strip()]:
             resolved_labels = standardize_labels(raw_topic_label, label_mapping)
             standardized_topic_labels.update(resolved_labels)

        standardized_topic_labels_list = sorted(list(standardized_topic_labels))

        # Select only one topic label: the first one alphabetically if multiple exist.
        # If no standardized labels are found, the cleaned topic label will be an empty string.
        cleaned_topic_label = standardized_topic_labels_list[0] if standardized_topic_labels_list else ''

        # Standardize Document Type Labels (returns a list of unique standardized types)
        raw_doctype_labels_string = row.get('Type Labels', '')
        
        # Process each raw document type label through standardize_labels individually
        standardized_doctype_labels = set()
        for raw_doctype_label in [label.strip() for label in raw_doctype_labels_string.split(',') if label.strip()]:
             resolved_doctype_labels = standardize_labels(raw_doctype_label, label_mapping)
             standardized_doctype_labels.update(resolved_doctype_labels)

        standardized_doctype_labels_list = sorted(list(standardized_doctype_labels))

        # Document type labels can still be multiple, join them with commas
        cleaned_doctype_labels = ', '.join(standardized_doctype_labels_list)
        
        # Update the row with cleaned labels
        row['Topic Labels'] = cleaned_topic_label # Assign single topic label
        row['Type Labels'] = cleaned_doctype_labels # Assign comma-separated type labels
        
        cleaned_data.append(row)

print(f"Writing cleaned data to: {output_csv_path}")
# Write the cleaned data to a new CSV file
with open(output_csv_path, mode='w', newline='', encoding='utf-8') as outfile:
    writer = csv.DictWriter(outfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(cleaned_data)

print(f"Cleaned data saved to {output_csv_path}")

# Update train_model.py to use the new cleaned CSV
# Read the content of train_model.py
# Assuming train_model.py is in the same directory as clean_labels.py (backend/)
with open('train_model.py', 'r', encoding='utf-8') as f:
    train_model_content = f.read()

# Replace the old csv_path with the new one
# The cleaned CSV is in the same directory as train_model.py and train_model.py expects this relative path
new_train_model_content = train_model_content.replace(
    "csv_path = 'NLP documents bank - Sheet1.csv'",
    "csv_path = 'NLP documents bank - Sheet1_cleaned.csv'"
)

# Write the modified content back to train_model.py
# Assuming train_model.py is in the same directory as clean_labels.py (backend/)
with open('train_model.py', 'w', encoding='utf-8') as f:
    f.write(new_train_model_content)

print("Updated train_model.py to use the cleaned CSV file.")